# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

coverage:
  ignore:
    - "test/*"
    - "**/mocks/**"
    - "mocks/**"
    - "**/*.pb.go"
    - "**/logging.go"
    - "**/metrics.go"
    - "**/tracing.go"
