services:
  broker:
    image: nats:2.9.21-alpine
    command: "--config=/etc/nats/nats.conf"
    volumes:
      - ./../nats/:/etc/nats
    environment:
      - COCOS_NATS_PORT=${COCOS_NATS_PORT}
      - COCOS_NATS_HTTP_PORT=${COCOS_NATS_HTTP_PORT}
      - COCOS_NATS_JETSTREAM_KEY=${COCOS_NATS_JETSTREAM_KEY}
    ports:
      - ${COCOS_NATS_PORT}:${COCOS_NATS_PORT}
      - ${COCOS_NATS_HTTP_PORT}:${COCOS_NATS_HTTP_PORT}